services:

  spark-master:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
    ports:
      - '7077:7077'
      - '8080:8080'
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  spark-worker-1:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - '8082:8081'
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    depends_on:
      - spark-master

  jupyter:
    build:
      dockerfile: ./dockerfile_jupyter
    ports:
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
      - '8888:8888'
    volumes:
      - ./data:/data
      - ./scripts:/home/jovyan/work/scripts
      - ./notebooks:/home/jovyan/work/notebooks
    depends_on:
      - spark-master
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
