FROM apache/airflow:2.9.0

USER root

# Install OpenJDK
RUN apt update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Set JAVA_HOME
#ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-arm64/
RUN export JAVA_HOME

USER airflow
COPY requirements_airflow.txt .
RUN pip install --no-cache-dir apache-airflow==${AIRFLOW_VERSION}
RUN pip install --no-cache-dir -r requirements_airflow.txt && rm requirements_airflow.txt

#RUN export PACKAGES="io.delta:delta-core_2.12:3.1.0"
#RUN export PYSPARK_SUBMIT_ARGS="--packages ${PACKAGES} pyspark-shell"
